### ISSUE TITLE
Keyboard Haptic Feedback doesn't work

### ISSUE THREAD

**Issue by BLINK1337** [CPDigitalDarkroom/HideMeX-iOS-10#6]
As title says, it doesn't work at all.
iPhone 6+ 10.2

**Comment by CPDigitalDarkroom** [comment]
Update, this should be working now. Can you check and let me know.

**Comment by BLINK1337** [comment]
Still get nothing. I've tried toggling off and on but nothing changes still.

**Comment by BLINK1337** [comment]
Still get nothing. I've tried toggling off and on but nothing changes still.

**Comment by Jerzerak** [comment]
This is working for me on a 6s+ running 10.2 w/ HideMeX v1.0.6
